In [ ]:
import torch
a=torch.arange(0,40,1).reshape(2,5,4)
print(a)
print(a.sum(axis=0))
print(a.sum(axis=1))
print(a.sum(axis=2))
print(a.sum(axis=[0,1])) #先对0轴求和，再对1轴求和，也可以先对1轴求和，再对0轴求和



tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11],
         [12, 13, 14, 15],
         [16, 17, 18, 19]],

        [[20, 21, 22, 23],
         [24, 25, 26, 27],
         [28, 29, 30, 31],
         [32, 33, 34, 35],
         [36, 37, 38, 39]]])
tensor([[20, 22, 24, 26],
        [28, 30, 32, 34],
        [36, 38, 40, 42],
        [44, 46, 48, 50],
        [52, 54, 56, 58]])
tensor([[ 40,  45,  50,  55],
        [140, 145, 150, 155]])
tensor([[  6,  22,  38,  54,  70],
        [ 86, 102, 118, 134, 150]])
tensor([180, 190, 200, 210])


In [10]:
# 维度的个数不发生变化
print(a.sum(axis=1,keepdim=True))
a.sum(axis=1,keepdim=True).shape # torch.Size([2, 1, 4])

tensor([[[ 40,  45,  50,  55]],

        [[140, 145, 150, 155]]])


torch.Size([2, 1, 4])