# numpy的创建


## ndarray特性
- 多维性
- 同质性
- 高效性

### 多维性

In [2]:
import numpy as np

# 创建0维数据
arr = np.array(1)
print("维度：", arr.ndim)

维度： 0


In [ ]:
arr = np.array([1, 2, 3, 4])
print(arr)
print("维度：", arr.ndim)

In [ ]:
arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr)
print("维度：", arr.ndim)

### 同质性

In [ ]:
arr = np.array([1, "2"])  # 不同的数据类型会被强制转化成相同的数据类型
print(arr)

In [ ]:
arr = np.array([1, 2.5])  # 不同的数据类型会被强制转化成相同的数据类型
print(arr) # [1.  2.5] 为浮点数

## ndarray的属性

- shape：数组的形状
- ndim: 维度数量
- size: 总元素个数
- dtype：元素的类型
- T：转置数组
- itemsize：每个元素的字节大小
- nbytes：数组占用的总字节数
- flags: 数组的内存存储形式，是否为连续存储

## ndarray的创建

### 基础构造

In [ ]:
# 基础的创建
arr = np.array([1, 2, 3], dtype=np.float32) # 32位浮点数s
print(arr)

# copy
arr1 = np.copy(arr)
print(arr1)
id(arr1) == id(arr) # false

## 预定义形状

In [ ]:
arr = np.zeros((2, 3)) # 全0
print(arr)
arr1 = np.ones((2, 3),dtype=int) # 全1
print(arr1)
arr3 = np.empty((2, 3)) # 空数组
print(arr3)
arr4 = np.full((2, 3), 5) # 全5
print(arr4)
arr5 = np.zeros_like(arr4) # 形状像arr4，填充0
print(arr5)


## 数值范围

In [ ]:
# 等差数列
arr = np.arange(1, 10, 1)  # start, end , 步长
print(arr)
# 等间隔数列
arr = np.linspace(1, 10, 5)  # start, end, 元素个数
print(arr)
# 对数数列: 以2为底，1-10之间取5个元素，做幂运算
arr = np.logspace(0, 4, 3, base=2)  # start, end, 元素个数
print(arr)

## 特殊矩阵

In [ ]:
# 单位矩阵：主对角线为1，其他元素为0
arr = np.eye(3, dtype=int)
print(arr)
# 对角矩阵：主对角线为非零元素，其他元素为0
arr = np.diag([1, 2, 3])
print(arr)

In [ ]:
# 随机数组的生成
arr = np.random.rand(2, 3)
print(arr)

# 生成指定范围区间的随机浮点数
arr = np.random.uniform(3, 6, (2, 3))  # 3,6是范围 (2,3)是形状
print(arr)
# 生成指定范围区间的随机整数
arr = np.random.randint(3, 6, (2, 3))  # 3,6是范围 (2,3)是形状
print(arr)

# 生成随机数列（正态分布：两边小，中间大）
arr = np.random.randn(2, 3)  # 0是均值，1是标准差 (2,3)是形状
print(arr)

# 设置随机种子
np.random.seed(42) # 42是种子，固定随机数的生成
arr = np.random.rand(2, 3)
print(arr)

# ndarray的数据类型

| 类别 | dtype 名称 | 代码/别名 | 位宽 | 说明/范围 |
|---|---|---|---|---|
| 有符号整型 | `int8` | `'i1'`, `np.int8` | 8 位 | −128 到 127 |
| 有符号整型 | `int16` | `'i2'`, `np.int16` | 16 位 | −32768 到 32767 |
| 有符号整型 | `int32` | `'i4'`, `np.int32` | 32 位 | −2,147,483,648 到 2,147,483,647 |
| 有符号整型 | `int64` | `'i8'`, `np.int64` | 64 位 | −9.22e18 到 9.22e18 |
| 有符号整型 | `intp` | `'p'`, `np.intp` | 平台相关 | 与指针大小相同（32/64 位） |
| 无符号整型 | `uint8` | `'u1'`, `np.uint8` | 8 位 | 0 到 255 |
| 无符号整型 | `uint16` | `'u2'`, `np.uint16` | 16 位 | 0 到 65535 |
| 无符号整型 | `uint32` | `'u4'`, `np.uint32` | 32 位 | 0 到 4.29e9 |
| 无符号整型 | `uint64` | `'u8'`, `np.uint64` | 64 位 | 0 到 1.84e19 |
| 无符号整型 | `uintp` | `'P'`, `np.uintp` | 平台相关 | 与指针大小相同（32/64 位） |
| 浮点型 | `float16` | `'f2'`, `np.float16` | 16 位 | 半精度浮点 |
| 浮点型 | `float32` | `'f4'`, `np.float32` | 32 位 | 单精度浮点 |
| 浮点型 | `float64` | `'f8'`, `np.float64` | 64 位 | 双精度浮点 |
| 浮点型 | `longdouble` | `'g'`, `np.longdouble` | 平台相关 | 扩展精度（常见 80/96/128 位） |
| 复数型 | `complex64` | `'c8'`, `np.complex64` | 64 位 | 两个 `float32`（实+虚） |
| 复数型 | `complex128` | `'c16'`, `np.complex128` | 128 位 | 两个 `float64`（实+虚） |
| 复数型 | `clongdouble` |  | 平台相关 | 两个 `longdouble`（实+虚） |
| 布尔型 | `bool_` | `'?'`, `np.bool_` | 8 位 | 布尔值 True/False |
| 字节串 | `S<n>` | `'S'` | n 字节 | 固定长度字节串，如 `S10` |
| Unicode 字符串 | `U<n>` | `'U'` | n 字符 | 固定长度 Unicode 串，如 `U10` |
| Python 对象 | `object_` | `'O'`, `np.object_` | 指针大小 | 任意 Python 对象引用 |
| 原始字节 | `void` | `'V'` | n 字节 | 原始数据/结构化字段 |
| 日期时间 | `datetime64[单位]` | `'M8[unit]'` | 64 位 | 单位 `Y,M,W,D,h,m,s,ms,us,ns` |
| 时间差 | `timedelta64[单位]` | `'m8[unit]'` | 64 位 | 与 `datetime64` 相同单位 |

使用示例：
- 指定整型：`np.array([1, 2, 3], dtype=np.int32)`
- 指定浮点：`np.array([1, 2, 3], dtype='f8')`  # float64
- 指定复数：`np.array([1+2j, 3+4j], dtype=np.complex128)`
- 指定字节串：`np.array([b'a', b'bb'], dtype='S2')`
- 指定 Unicode：`np.array(['你', '好'], dtype='U1')`
- 指定时间：`np.array(['2025-01-01'], dtype='datetime64[D]')`
- 指定时间差：`np.array([1], dtype='timedelta64[h]')`

小贴士：
- `longdouble` 精度依赖平台，macOS 常与 `float64` 一样。
- 长度受限的字符串会截断或填充；查看 `arr.itemsize`、`arr.nbytes`。

# 索引与切片

In [ ]:
# 一维数组的索引与切片
arr = np.random.randint(1, 100, 30)
print(arr)
print(arr[10])
print(arr[:])  # 获取全部的数据
print(arr[2:5])  # 取下标2-4的数据
print(arr[slice(2, 5)])  # 取下标2-4的数据
print(arr[arr > 10])  # bool索引
print(arr[(arr > 10) & (arr < 70)])  # bool索引

In [ ]:
# 二维数组的索引与切片
arr = np.random.randint(1, 100, (3, 4))
print(arr)
print(arr[1, 2])  # 取下标为(1,2)的数据
print(arr[1, :])  # 取下标为(1,*)的数据
print(arr[:, 2])  # 取下标为(*,2)的数据
print(arr[1, 2:4])  # 取下标为(1,2-3)的数据

print(arr[arr > 50])  # 取大于50的数据,返回一个一维数组
print(arr[2][arr[2] > 50]) # 取第2行大于50的数据

# ndarray的运算

In [ ]:
# 算数运算
a = np.array([1,2,3])
b = np.array([4,5,6])
print(a + b)
print(a - b)
print(a * b)
print(a / b)


In [ ]:
# 二维数组的运算
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[7,8,9],[10,11,12]])
print(a)
print(b)
print(a + b)
print(a - b)
print(a * b)
print(a / b)


## 广播机制

In [ ]:
# 广播机制
# 1.获取形状 2.比较形状，是否可以进行广播(所有对应维度的大小要么相等，要么其中有一个为1) 3.广播
a = np.array([[1, 2, 3]])  # 1*3
b = np.array([[4], [5], [6]])  # 3*1
"""
a
1 2 3
1 2 3
1 2 3
b
4 4 4
5 5 5
6 6 6
"""
print(a)
print(b)
print(a + b)

In [ ]:
# 不可以广播
a = np.array([1,2,3]) # 1*3
b = np.array([4,5]) # 1*2

print(a)
print(b)
print(a + b) # 报错

# 矩阵运算


In [85]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[1, 2], [3, 4], [5, 6]])

print(a)
print(b)
# print(a.dot(b))
print(a@b)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]
[[22 28]
 [49 64]]


# 基本数学函数

In [88]:
## 计算平方根
print(np.sqrt(2))
print(np.sqrt([2, 4, 9]))

## 计算指数：e^x次方
print(np.exp(2))
print(np.exp([1, 2, 3]))

1.4142135623730951
[1.41421356 2.         3.        ]
7.38905609893065
[ 2.71828183  7.3890561  20.08553692]


# 统计函数

In [95]:
arr = np.random.randint(1, 20, 8)
print(arr)

# 求和
print(np.sum(arr))

# 求平均
print(np.mean(arr))

# 求中位数:排序后中间的数值
print(np.median(arr))

# 计算标准差、方差
# 标准差是数据分布的离散程度，方差是标准差的平方
# 标准差计算公式：(Xi - X的平均值)^2 求和 除以 数据数量
print(np.std(arr))
print(np.var(arr))



[ 2 13  6  5  1  6  6 16]
55
6.875
6.0
4.807221130757353
23.109375


In [99]:
# 计算分位数
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
# 计算25%分位数，有25%的数据小于等于该值
print(np.percentile(arr, 25))
# 累计和、累计积
arr = np.array([1,2,3])
print(np.sum(arr))
print(np.cumsum(arr))
print(np.cumprod(arr))

3.25
6
[1 3 6]
[1 2 6]


# 比较函数
比较是否大于、小于、等于、逻辑与、或、非

In [ ]:
# 是否大于
print(np.greater([3, 4, 5, 6, 7], 4))
# 是否小于
print(np.less([3, 4, 5, 6, 7], 4))
# 是否等于
print(np.equal([3, 4, 5, 6, 7], 4))
print(np.equal([3, 4, 5, 6, 7], [3, 4, 5, 6, 7]))

# 逻辑运算
print(np.logical_and([0, 0], [1, 1]))
print(np.logical_or([0, 0], [1, 1]))
print(np.logical_not([1, 0])) # 取反1为False，0为True

[False False  True  True  True]
[ True False False False False]
[False  True False False False]
[ True  True  True  True  True]
[False False]
[ True  True]
[False  True]


In [109]:
# 检查元素是否有一个元素为True
print(np.any([0, 0, 0]))
print(np.any([0, 1, 0]))
# 检查是否所有元素为True
print(np.all([1, 1, 1]))
print(np.all([1, 0, 1]))

False
True
True
False


In [112]:
# 自定义条件
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(np.where(arr > 5))
print(np.where(arr < 3, arr, 0))  # 小于3的元素不变，大于等于3的元素设为0
print(np.where(arr < 3, 1, 0))  # 小于3的元素变为1，大于等于3的元素设为0

(array([5, 6, 7, 8, 9]),)
[1 2 0 0 0 0 0 0 0 0]
[1 1 0 0 0 0 0 0 0 0]


In [6]:
score = np.random.randint(50, 100, 20)
print(score)
print(np.where(score >= 60, "及格", "不及格"))
# 可以嵌套表示
print(np.where(score < 60, "不及格", np.where(score < 80, "中等", "优秀")))

[52 89 75 60 84 51 85 53 76 60 54 81 80 93 97 95 53 50 73 81]
['不及格' '及格' '及格' '及格' '及格' '不及格' '及格' '不及格' '及格' '及格' '不及格' '及格' '及格' '及格'
 '及格' '及格' '不及格' '不及格' '及格' '及格']
['不及格' '优秀' '中等' '中等' '优秀' '不及格' '优秀' '不及格' '中等' '中等' '不及格' '优秀' '优秀' '优秀'
 '优秀' '优秀' '不及格' '不及格' '中等' '优秀']


In [7]:
# np.select(条件， 返回的结果)
print(
    np.select(
        [
            score > 80,
            (score > 60) & (score < 80),
            score < 60,
        ],
        ["优秀", "良好", "不及格"],
        default="未知",
    )
)

['不及格' '优秀' '良好' '未知' '优秀' '不及格' '优秀' '不及格' '良好' '未知' '不及格' '优秀' '未知' '优秀'
 '优秀' '优秀' '不及格' '不及格' '良好' '优秀']


# 排序函数

In [ ]:
np.random.seed(0)
arr = np.random.randint(1, 100, 20)
# print(arr)
# arr.sort() # 改变原数组
print(arr)
print(np.sort(arr)) # 不改变原数组
print(np.argsort(arr)) # 返回数组排序后数组元素在原数组中的索引


[45 48 65 68 68 10 84 22 37 88 71 89 89 13 59 66 40 88 47 89]
[10 13 22 37 40 45 47 48 59 65 66 68 68 71 84 88 88 89 89 89]
[ 5 13  7  8 16  0 18  1 14  2 15  3  4 10  6 17  9 11 12 19]


In [13]:
#去重函数
print(np.unique(arr))

[10 13 22 37 40 45 47 48 59 65 66 68 71 84 88 89]


# 其它

In [14]:
# 数组的拼接
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


In [ ]:
# 数组的分割
arr = np.array([1, 2, 3, 4, 5, 6])
print(np.split(arr, 3))  # 切割成3份
print(np.split(arr, [2, 3, 5]))  # 按照切割位置的索引，切割成4份

[array([1, 2]), array([3, 4]), array([5, 6])]
[array([1, 2]), array([3]), array([4, 5]), array([6])]


In [19]:
# 调整数组的形状
print(arr.reshape(2, 3))  # 调整为2行3列的数组

[[1 2 3]
 [4 5 6]]
